component:
  prompt:
    - name
  temples:
    - template: ./templates/component.template
      output: './src/components/{{ name }}/index.js'
    - output: './src/components/{{ name }}/styles.module.scss'

page:
  prompt:
    - name
  temples:
    - template: ./templates/component.template
      output: './src/routes/{{ name }}/index.js'
    - template: ./templates/page.template
      output: './src/pages/{{ kebab name }}.js'
    - output: './src/routes/{{ name }}/styles.module.scss'
